spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring?characterEncoding=utf-8&useSSL=false
server:
  port: 18099
mybatis:
  mapper-locations: classpath:mapperXml/*.xml
